language: generic
udo: required
services:
  -docker

before_install:
  - docker build -t reachkarthik-mca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true reachkarthik-mca/docker-react npm run test -- --coverage


